In [ ]:
#teste

## **0. Set-Up**

In [22]:
#Libraries
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import random
from PIL import Image
from tqdm import tqdm
import scipy.stats as ss
import torch
import torchvision.transforms as T
import torchvision.models as models
from tqdm import tqdm
import umap

import missingno as msno

In [28]:
base_path = "./data" 

image_dirs = [
    "HAM10000_images_part_1",
    "HAM10000_images_part_2",
    "ISIC2018_Task3_Test_Images"
]

image_paths = []

In [29]:
metadata_path = os.path.join(base_path, "HAM10000_metadata")
metadata_df = pd.read_csv(metadata_path, sep=",")
metadata_df.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,dataset
0,HAM_0000118,ISIC_0027419,bkl,histo,80.0,male,scalp,vidir_modern
1,HAM_0000118,ISIC_0025030,bkl,histo,80.0,male,scalp,vidir_modern
2,HAM_0002730,ISIC_0026769,bkl,histo,80.0,male,scalp,vidir_modern
3,HAM_0002730,ISIC_0025661,bkl,histo,80.0,male,scalp,vidir_modern
4,HAM_0001466,ISIC_0031633,bkl,histo,75.0,male,ear,vidir_modern

In [32]:
merged_df_path = os.path.join(base_path, "merged_df_cleaned.csv")
merged_df = pd.read_csv(merged_df_path, sep=",")
merged_df.head()

,image_id,image_path,lesion_id,dx,dx_type,age,sex,localization,dataset,img_mean,img_std,width,height,umap_dist,is_outlier,cleaned_path
0,ISIC_0028291,/content/drive/MyDrive/MDSAA-DS/DL-project/dat...,HAM_0006253,mel,histo,65.0,male,back,vidir_modern,0.666128,0.154030,600,450,1.802865,False,/content/drive/MyDrive/MDSAA-DS/DL-project/dat...
1,ISIC_0028308,/content/drive/MyDrive/MDSAA-DS/DL-project/dat...,HAM_0003752,bkl,histo,50.0,female,chest,rosendahl,0.621565,0.091182,600,450,0.999917,False,/content/drive/MyDrive/MDSAA-DS/DL-project/dat...
2,ISIC_0028286,/content/drive/MyDrive/MDSAA-DS/DL-project/dat...,HAM_0005470,nv,follow_up,30.0,female,trunk,vidir_molemax,0.662481,0.200656,600,450,3.714251,False,/content/drive/MyDrive/MDSAA-DS/DL-project/dat...
3,ISIC_0028288,/content/drive/MyDrive/MDSAA-DS/DL-project/dat...,HAM_0004709,mel,histo,65.0,male,back,rosendahl,0.694768,0.142947,600,450,1.436014,False,/content/drive/MyDrive/MDSAA-DS/DL-project/dat...
4,ISIC_0028313,/content/drive/MyDrive/MDSAA-DS/DL-project/dat...,HAM_0004166,nv,follow_up,45.0,male,back,vidir_molemax,0.672074,0.212765,600,450,3.718916,False,/content/drive/MyDrive/MDSAA-DS/DL-project/dat...